name: Demo CI Action

on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1

      - name: install node dependencies for testing
        run: npm install

      - name: run node tests to audit codebase
        run: npm test

  build_docker_image:
    name: build docker image for image repository
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        
      - name: install runtime dependencies only
        run: npm i --omit=dev
        
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: build the push to docker hub
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.HUB_USERNAME }}/external:a.${{ github.run_number }}
